'use strict';
// Создаем элементы
const bodyContainer = document.createElement('div');
const heading = document.createElement('h1');
const description = document.createElement('p');
const form = document.createElement('form');
const inputColumn = document.createElement('div');
const container1 = document.createElement('div');
const container2 = document.createElement('div');
const firstNameContainer = document.createElement('div');
const firstNameLabel = document.createElement('label');
const firstNameInput = document.createElement('input');
const displayNameContainer = document.createElement('div');
const displayNameLabel = document.createElement('label');
const displayNameInput = document.createElement('input');
const passwordContainer = document.createElement('div');
const passwordLabel = document.createElement('label');
const passwordInput = document.createElement('input');
const lastNameContainer = document.createElement('div');
const lastNameLabel = document.createElement('label');
const lastNameInput = document.createElement('input');
const emailContainer = document.createElement('div');
const emailLabel = document.createElement('label');
const emailInput = document.createElement('input');
const passwordConfirmationContainer = document.createElement('div');
const passwordConfirmationLabel = document.createElement('label');
const passwordConfirmationInput = document.createElement('input');
const flexboxBox = document.createElement('div');
const box1 = document.createElement('div');
const box1Input = document.createElement('input');
const box1Label = document.createElement('label');
const box1Description = document.createElement('p');
const box2 = document.createElement('div');
const box2Input = document.createElement('input');
const box2Label = document.createElement('label');
const box2Description = document.createElement('p');
const marketingCheckboxContainer = document.createElement('div');
const marketingCheckboxInput = document.createElement('input');
const marketingCheckboxLabel = document.createElement('label');
const buttonContainer = document.createElement('div');
const submitButton = document.createElement('input');

// Добавляем классы к элементам
bodyContainer.id = 'body-conteiner';
inputColumn.id = 'input-column';
container1.className = 'container';
container2.className = 'container';
firstNameContainer.className = 'input-container';
displayNameContainer.className = 'input-container';
passwordContainer.className = 'input-container';
lastNameContainer.className = 'input-container';
emailContainer.className = 'input-container';
passwordConfirmationContainer.className = 'input-container';
flexboxBox.id = 'flexbox-box';
box1.className = 'box';
box2.className = 'box';
marketingCheckboxContainer.className = 'checkbox-container';
buttonContainer.className = 'button-container';

// Задаем атрибуты и текст элементам
heading.textContent = 'CREATE AN ACCOUNT';
description.textContent = 'We always keep your name and email address private';
firstNameLabel.htmlFor = 'first-name';
firstNameInput.type = 'text';
firstNameInput.id = 'first-name';
firstNameInput.placeholder = 'First name';
displayNameLabel.htmlFor = 'display-name';
displayNameInput.type = 'text';
displayNameInput.id = 'display-name';
displayNameInput.placeholder = 'Display name';
passwordLabel.htmlFor = 'password';
passwordInput.type = 'password';
passwordInput.id = 'password';
passwordInput.name = 'password';
passwordInput.placeholder = 'Password';
lastNameLabel.htmlFor = 'last-name';
lastNameInput.type = 'text';
lastNameInput.id = 'last-name';
lastNameInput.placeholder = 'Last name';
emailLabel.htmlFor = 'email';
emailInput.type = 'email';
emailInput.id = 'email';
emailInput.name = 'email';
emailInput.placeholder = 'Email Address';
passwordConfirmationLabel.htmlFor = 'password-confirmation';
passwordConfirmationInput.type = 'password';
passwordConfirmationInput.id = 'password-confirmation';
passwordConfirmationInput.name = 'password-confirmation';
passwordConfirmationInput.placeholder = 'Password Confirmation';
box1Input.type = 'radio';
box1Input.id = 'first-choice';
box1Input.name = 'choice';
box1Input.value = 'first-choice';
box1Label.htmlFor = 'first-choice';
box1Label.textContent = 'Join As a Buyer';
box1Description.textContent = 'I am looking for a Name, Logo or Tagline for my business, brand or product.';
box2Input.type = 'radio';
box2Input.id = 'second-choice';
box2Input.name = 'choice';
box2Input.value = 'second-choice';
box2Label.htmlFor = 'second-choice';
box2Label.textContent = 'Join As a Creative or Marketplace Seller';
box2Description.textContent = 'I plan to submit name ideas, Logo design or sell names in Domain Marketplace.';
marketingCheckboxInput.type = 'checkbox';
marketingCheckboxInput.id = 'checkbox';
marketingCheckboxLabel.htmlFor = 'checkbox';
marketingCheckboxLabel.textContent = 'Allow Squadhelp to send marketing/promotional offers from time to time';
submitButton.type = 'submit';
submitButton.value = 'Create Account';

// Строим структуру элементов
firstNameContainer.appendChild(firstNameLabel);
firstNameContainer.appendChild(firstNameInput);
displayNameContainer.appendChild(displayNameLabel);
displayNameContainer.appendChild(displayNameInput);
passwordContainer.appendChild(passwordLabel);
passwordContainer.appendChild(passwordInput);
lastNameContainer.appendChild(lastNameLabel);
lastNameContainer.appendChild(lastNameInput);
emailContainer.appendChild(emailLabel);
emailContainer.appendChild(emailInput);
passwordConfirmationContainer.appendChild(passwordConfirmationLabel);
passwordConfirmationContainer.appendChild(passwordConfirmationInput);
container1.appendChild(firstNameContainer);
container1.appendChild(displayNameContainer);
container1.appendChild(passwordContainer);
container2.appendChild(lastNameContainer);
container2.appendChild(emailContainer);
container2.appendChild(passwordConfirmationContainer);
inputColumn.appendChild(container1);
inputColumn.appendChild(container2);
box1.appendChild(box1Input);
box1.appendChild(box1Label);
box1.appendChild(box1Description);
box2.appendChild(box2Input);
box2.appendChild(box2Label);
box2.appendChild(box2Description);
flexboxBox.appendChild(box1);
flexboxBox.appendChild(box2);
marketingCheckboxContainer.appendChild(marketingCheckboxInput);
marketingCheckboxContainer.appendChild(marketingCheckboxLabel);
buttonContainer.appendChild(submitButton);

form.appendChild(inputColumn);
form.appendChild(flexboxBox);
form.appendChild(marketingCheckboxContainer);
form.appendChild(buttonContainer);
bodyContainer.appendChild(heading);
bodyContainer.appendChild(description);
bodyContainer.appendChild(form);

document.body.appendChild(bodyContainer);
